FROM python:3.7.9

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY . .

RUN pip install -r requirements-fastapi.txt

EXPOSE 8000

WORKDIR /app/src

CMD [ "uvicorn", "api:app", "--host", "0.0.0.0"]