version: '3.8'

services:
  traefik:
    image: traefik
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/services/traefik:/etc/traefik
      - $PWD/etc/cert:/etc/cert

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    labels:
      - traefik.enable=true
      - traefik.http.routers.app-http.rule=Host(`api.spanking.wiki`)
      - traefik.http.routers.app-http.tls=true
    volumes:
      - ./src:/app/src:cached

  discord:
    build:
      context: .
      dockerfile: Dockerfile-discord
    command: python discord_bot.py
    ports:
      - 9090:8080
    working_dir: /app/src

  db:
    image: mariadb:10.4
    command: --max_allowed_packet=64M
    env_file: env/db.env
    ports:
      - 3307:3306
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 9999:80
    environment:
      - PMA_ARBITRARY=1

volumes:
    dbdata:
